### PR TITLE
C rewrite

### LINKED ISSUE #2: Use output manager protocol
~~Not ready yet. Doesn't show disabled outputs.~~

~~https://cgit.freedesktop.org/wayland/wayland-protocols/tree/unstable/xdg-output/xdg-output-unstable-v1.xml~~

### LINKED ISSUE #8: Exit when sway exits
Probably read from the IPC socket and exit if that fails

### LINKED ISSUE #16: Matching configuration: None
`.config/kanshi/config` is

```
{
  output VGA-1 enable
  output LVDS-1 disable
}
{
  output LVDS-1 enable
  output VGA-1 disable
}
```

`kanshi` gives

```
Connected outputs:
output VGA-1 vendor PHL product Philips 170S serial VN  004623
output LVDS-1 vendor SEC product 0x3651 serial 0x0
Matching configuration: None
```

As per IRC have tried the full reported output names in the config, also with `output VGA-1 vendor PHL enable` etc., and with `output "LVDS-1" disable`

I've also tried all the above with `kanshi -s kanshi -f sway --primary-workspace "LVDS-1"`.

(I'm assuming the expected behaviour should be to toggle between the 'profiles'.)

### LINKED ISSUE #17: Add support for transform (i.e rotation)
Hi there,

Great job you're doing here.
Adding `transform 90` (sway screen rotation) to an output in `.config/kanshi/config` causes the parser to silently fail. Upon inspection, I noticed the frontend and store don't seem to handle screen rotation. I think this would be fairly easy addition and much appreciated feature for portrait output lovers.

Cheers,

### LINKED ISSUE #18: Migrate away from nom
Use something else instead (pest?).

### LINKED ISSUE #20: kanshi prints matched configuration and exits
I don't really understand how to use this program. Judging from the description I'd guess that kanshi monitors external screen connect and disconnect events and adjusts display configuration accordingly.
I have the following config:
```
{
    output eDP-1 vendor SHP product 0x144A serial 0x0 scale 2
}

{
    output eDP-1 vendor SHP product 0x144A serial 0x0 scale 2 position 0,1050
    output DP-1 vendor SAM product SyncMaster serial H9XPC04698 position 0,0
}
```
It looks like it successfully matches configurations for both cases - a single laptop screen and a laptop screen with an external monitor.
This is the `kanshi` output in casae of a single laptop screen:
```
Connected outputs:
output eDP-1 vendor SHP product 0x144A serial 0x0
Matching configuration: Some([MatchedOutput { connected: ConnectedOutput { name: "eDP-1", edid: EDID { header: Header { vendor: ['S', 'H', 'P'], product: 5194, serial: 0, week: 23, year: 25, version: 1, revision: 4 }, display: Display { video_input: 165, width: 29, height: 17, gamma: 120, features: 14 }, chromaticity: (), established_timing: (), standard_timing: (), descriptors: [DetailedTiming, DetailedTiming, UnspecifiedText("RXN49\u00b6LQ133Z1"), Unknown([2, 65, 3, 40, 0, 18, 0, 0, 11, 1, 10, 32, 32])] } }, saved: SavedOutput { name: "eDP-1", vendor: "SHP", product: "0x144A", serial: "0x0", enabled: true, width: 0, height: 0, rate: 0.0, x: 0, y: 0, primary: false, scale: 2 } }])
output eDP-1 position 0,0 scale 2
```

This is the `kanshi` output in case of a laptop screen and a monitor plugged in via USB-C port (with HDMI to USB-C adapter if that matters):

```
Connected outputs:
output eDP-1 vendor SHP product 0x144A serial 0x0
output DP-1 vendor SAM product SyncMaster serial H9XPC04698
Matching configuration: Some([MatchedOutput { connected: ConnectedOutput { name: "eDP-1", edid: EDID { header: Header { vendor: ['S', 'H', 'P'], product: 5194, serial: 0, week: 23, year: 25, version: 1, revision: 4 }, display: Display { video_input: 165, width: 29, height: 17, gamma: 120, features: 14 }, chromaticity: (), established_timing: (), standard_timing: (), descriptors: [DetailedTiming, DetailedTiming, UnspecifiedText("RXN49\u00b6LQ133Z1"), Unknown([2, 65, 3, 40, 0, 18, 0, 0, 11, 1, 10, 32, 32])] } }, saved: SavedOutput { name: "eDP-1", vendor: "SHP", product: "0x144A", serial: "0x0", enabled: true, width: 0, height: 0, rate: 0.0, x: 0, y: 1050, primary: false, scale: 2 } }, MatchedOutput { connected: ConnectedOutput { name: "DP-1", edid: EDID { header: Header { vendor: ['S', 'A', 'M'], product: 542, serial: 1212232240, week: 50, year: 17, version: 1, revision: 3 }, display: Display { video_input: 128, width: 43, height: 27, gamma: 120, features: 42 }, chromaticity: (), established_timing: (), standard_timing: (), descriptors: [DetailedTiming, RangeLimits, ProductName("SyncMaster"), SerialNumber("H9XPC04698")] } }, saved: SavedOutput { name: "DP-1", vendor: "SAM", product: "SyncMaster", serial: "H9XPC04698", enabled: true, width: 0, height: 0, rate: 0.0, x: 0, y: 0, primary: false, scale: 0 } }])
output eDP-1 position 0,1050 scale 2
output DP-1 position 0,0
```
As you see `kanshi` prints out commands suitable for `swaymsg` (I'm using sway) but nothing actually happens - the program just exits.
Am I missing something here?

### LINKED ISSUE #24: kanshi  errors on startup
```
│ RUST_BACKTRACE=1 kanshi
Connected outputs:
output eDP-1 vendor CMN product 0x14D5 serial 0x0
thread 'main' panicked at 'called  on an  value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/libcore/result.rs:1009:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
   1: std::sys_common::backtrace::print
   2: std::panicking::default_hook::{{closure}}
   3: std::panicking::default_hook
   4: std::panicking::rust_panic_with_hook
   5: std::panicking::continue_panic_fmt
   6: rust_begin_unwind
   7: core::panicking::panic_fmt
   8: core::result::unwrap_failed
   9: <kanshi::store::KanshiStore as kanshi::store::Store>::list_configurations
  10: kanshi::main
  11: std::rt::lang_start::{{closure}}
  12: std::panicking::try::do_call
  13: __rust_maybe_catch_panic
  14: std::rt::lang_start_internal
  15: main
  16: __libc_start_main
  17: _start
```

### LINKED ISSUE #25: kanshi produces the wrong parameters for position on sway
My configuration produces
```
$ kanshi 2>/dev/null
output eDP-1 disable
output DP-1 position 0,0 scale 1
```

If I try running the second line:
```
$ swaymsg "output DP-1 position 0,0 scale 1"
Error: Missing position argument (y).
```

This seems to be because position is marked as `x,y` rather than `x y`. The documentation on `man sway-output` specifies that x and y should be separated by a space and using a space instead seems to work:

```
$ swaymsg 'output DP-1 position 0 0'
<no error message>
```

### LINKED ISSUE #27: Compile error with Rust 1.34
```
  Compiling kanshi v0.2.1 (file:///home/martin/.cache/pikaur/build/kanshi-git/src/kanshi)
error: non-reference pattern used to match a reference (see issue #42640)
  --> src/frontend.rs:38:8
   |
38 |             for MatchedOutput{connected, saved} in config {
   |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: consider using a reference: `&MatchedOutput{connected, saved}`
```

### LINKED ISSUE #28: Release newer version
The current version of Kanshi available in cargo is from 2017, please consider releasing the latest as it's currently incompatible with sway 1.x due to incorrect output syntax.

### PR DESCRIPTION
**Pull request by emersion**
Remove all Rust code, replace it with C. Remove sway IPC and udev, replace it with the output-management protocol.

Differences with the Rust version:

* "res", "resoltution" are no longer accepted, use "mode"
* "pos" is no longer accepted, use "position"
* "vendor", "model" "serial" are no longer accepted, instead replace the output name with "<vendor> <model> <serial>"

TODO:

- [x] Basic parser
- [x] Basic output-management listener
- [x] Match profile
- [x] Apply profile
- [x] Add missing features to reach feature parity with the Rust version
- [x] Add docs

(Note: the diff stats contain the protocol so it doesn't really mean anything)

Fixes #28 
Fixes #27
Fixes #25
Fixes #24
Fixes #20
Fixes #18
Fixes #17
Fixes #16
Fixes #8
Fixes #2

### CODE REVIEW

**Comment by atouminet** [comment]
This is so bullshit

**Review by bwidawsk — COMMENTED** [review]
Have you considered libconfuse?

File: include/config.h [hunk 1]
```diff
@@ -0,0 +1,40 @@
...
+	bool enabled;
+	struct {
+		int width, height;
+		int refresh; // mHz
+	} mode;
+	struct {
+		int x, y;
+	} position;
+	float scale;
+	enum wl_output_transform transform;
```
Comment (bwidawsk) [inline include/config.h:29]: dpms field?

**Comment by emersion** [comment]
>Have you considered libconfuse?

I've considered using an external parser for a well-known file format, but I'd like to keep the configuration as close as sway's as possible.

File: include/config.h (hunk 1 above)
Comment (emersion) [reply include/config.h:29]: This was intentionally left out of the output-management protocol (see https://github.com/swaywm/wlr-protocols/pull/38), because DPMS is not about output management, it's about idling after a delay. I think DPMS should be handled by swayidle instead.

**Comment by emersion** [comment]
Let's start with this.
